Add support for elasticsearch Internal Users
kubedb/elasticsearch pull request #574
Opened 2022-04-25 11:36 UTC by raihankhan

Signed-off-by: raihankhan <raihan@appscode.com>

2022-05-09 12:32 UTC, kamolhasan requested changes

2022-05-09 12:32 UTC, kamolhasan commented on pkg/util/go-es/es_client_v6.go
> +func (es *ESClientV6) SyncCredentialFromSecret(secret *core.Secret) error {
Add comments

2022-05-09 12:32 UTC, kamolhasan commented on pkg/util/go-es/es_client_v7.go
> +	if res.StatusCode == http.StatusOK {
Use isError()

2022-05-10 04:21 UTC, raihankhan commented on pkg/admission/validator.go
> +	if err := amv.ValidateInternalUsers(db.Spec.InternalUsers, allowedInternalUsers, api.ResourceKindElasticsearch); err != nil {
done

2022-05-10 04:22 UTC, raihankhan commented on pkg/controller/appbinding.go
> +			return kutil.VerbUnchanged, errors.New("client-cert secret is missing")
Changed

2022-05-10 04:23 UTC, raihankhan commented on pkg/controller/appbinding.go
> +		if _, ok := clientCertSecret.Data[certlib.CACert]; !ok {
removed redundant check

2022-05-10 04:25 UTC, raihankhan commented on pkg/controller/elasticsearch.go
> +		if (version.Major() == 7 && version.Minor() >= 8) || version.Major() >= 8 {
fixed

2022-05-10 05:41 UTC, raihankhan commented on pkg/util/go-es/es_client_v7.go
> +	AdminClient *esv7.Client
Fixed

2022-05-10 05:53 UTC, raihankhan commented on pkg/util/go-es/api.go
>  func GetElasticClient(kc kubernetes.Interface, db *api.Elasticsearch, esVersion *catalog.ElasticsearchVersion, url string) (ESClient, error) {
Added

2022-05-10 06:18 UTC, raihankhan commented on pkg/distribution/elastic_stack/credential.go
> +		url := fmt.Sprintf("%v://%s.%s.svc:%d", es.db.GetConnectionScheme(), es.db.ServiceName(), es.db.GetNamespace(), api.ElasticsearchRestPort)
Added

2022-05-10 06:19 UTC, raihankhan commented on pkg/distribution/elastic_stack/credential.go
> +func (es *Elasticsearch) createOrSyncBuiltinUserCred(user string) (map[string]api.ElasticsearchUserSpec, error) {
FIxed

2022-05-10 09:28 UTC, raihankhan commented on pkg/distribution/elastic_stack/credential.go
> +		return err
created

2022-05-10 09:28 UTC, raihankhan commented on pkg/distribution/elastic_stack/credential.go
> +	internalUsers, err := es.createOrSyncBuiltinUserCred(string(api.ElasticsearchInternalUserKibanaSystem))
Algorithm modified

2022-05-10 09:28 UTC, raihankhan commented on pkg/util/go-es/es_client_v7.go
> +	b.WriteString(`{"password" : "`)
Fixed

2022-05-10 09:29 UTC, raihankhan commented on pkg/util/go-es/es_client_v7.go
> +	if res.StatusCode == http.StatusOK {
Fixed

2022-05-11 06:09 UTC, kamolhasan requested changes

2022-05-11 06:09 UTC, kamolhasan commented on pkg/util/go-es/api.go
> +	if !opt.Db.Spec.DisableSecurity && opt.Db.Spec.AuthSecret != nil {
Check whether the opt.Secret is empty or not?

2022-05-11 06:09 UTC, kamolhasan commented on pkg/util/go-es/api.go
> +	Kc        kubernetes.Interface
KClient
DB
ESVersion
URL

2022-05-11 06:09 UTC, kamolhasan commented on pkg/distribution/elastic_stack/credential.go
> +		if user, ok := in.Spec.InternalUsers[string(api.ElasticsearchInternalUserKibanaSystem)]; ok {
check, if map is nil. 
Then use make(map[]) to initialize.

2022-05-11 09:16 UTC, kamolhasan approved these changes
LGTM!

2022-05-11 09:27 UTC, merged